### ISSUE TITLE
The blackfriday pagkage not Run funcation

### ISSUE THREAD

**Issue by katechun** [yuedun/metal#1]
2019/05/02 01:46:44 INFO     ▶ 0001 Using 'metal' as 'appname'
2019/05/02 01:46:44 INFO     ▶ 0002 Initializing watcher...
metal/controllers
# metal/controllers
controllers/portal-ctrl.go:145:12: undefined: blackfriday.Run
2019/05/02 01:46:44 ERROR    ▶ 0003 Failed to build the application: # metal/controllers
controllers/portal-ctrl.go:145:12: undefined: blackfriday.Run

这个blackfriday 我使用go get github.com/russross/blackfriday  下载，  但是没有Run方法，这是怎么回事？

**Comment by yuedun** [comment]
> 
> 
> 2019/05/02 01:46:44 INFO ▶ 0001 Using 'metal' as 'appname'
> 2019/05/02 01:46:44 INFO ▶ 0002 Initializing watcher...
> metal/controllers
> # metal/controllers
> 
> controllers/portal-ctrl.go:145:12: undefined: blackfriday.Run
> 2019/05/02 01:46:44 ERROR ▶ 0003 Failed to build the application: # metal/controllers
> controllers/portal-ctrl.go:145:12: undefined: blackfriday.Run
> 
> 这个blackfriday 我使用go get github.com/russross/blackfriday 下载， 但是没有Run方法，这是怎么回事？

**Comment by yuedun** [comment]
@katechun 要使用v2版本 [https://github.com/russross/blackfriday](https://github.com/russross/blackfriday)在README中有说明，可以参考下
