### ISSUE TITLE
禁用自动生成目录问题

### ISSUE THREAD

**Issue by lifa1225** [yuedun/metal#2]
你好博主，从你的代码中获益匪浅，有个问题请教下：
editormd有办法去除“自动生成”目录这个配置吗？

![image](https://user-images.githubusercontent.com/59470742/115378896-9e567580-a203-11eb-9b15-47ee7b5f091e.png)

**Comment by yuedun** [comment]
> 
> 
> 你好博主，从你的代码中获益匪浅，有个问题请教下：
> editormd有办法去除“自动生成”目录这个配置吗？
> 
> ![image](https://user-images.githubusercontent.com/59470742/115378896-9e567580-a203-11eb-9b15-47ee7b5f091e.png)

实在不好意思，没注意到过您的issue，自动目录是由`[TOC]`这个标记生成的，这个并不是editormd的问题，而是markdown标记的问题
